"""S11 unit L3: the effects unit table (`coverage/effects_unit_table.py`, DESIGN-s11 §5.3 G1, §5.4).

The join of the reference drivers' ASTs, the REFERENCE goldens and the M7 transaction-block catalogue is regenerated byte-equal;
synthetic sources carry a negative control for each rule of an entry (a driver call of another method, a block whose buckets do
not cover the durable writes, a golden unit with no rule-6 case); the G1 resolutions are exactly the table's entries on rows
that carry the pending item.
"""

import json
import subprocess
import sys

import pytest
from _layout import REPO as ROOT

sys.path.insert(0, str(ROOT / "coverage"))
try:
    import effects_unit_table as eut
finally:
    sys.path.remove(str(ROOT / "coverage"))

DRIVER = '''
def run(api):
    return {"unit": {v: scenario(api, v) for v in ("success", "a_failure_at_row")}}

def scenario(api, variant):
    return api.store.{call}(variant)
'''
CASE = {"durable_writes": [["research_rows", ""]], "effects": []}


def block(n, writes, scope="Svc.unit", module="codex_harness.application.svc"):
    return {"key": f"{module}:{scope}#{n}", "line": n * 10, "literal_writes": writes, "module": module, "scope": scope}


def join(call="unit", golden=None, blocks=None, imports="from codex_harness.application import svc\n"):
    golden = {"unit": {"success": CASE, "a_failure_at_row": CASE}} if golden is None else golden
    blocks = [block(1, ["research_rows"])] if blocks is None else blocks
    path = "compare/drivers/reference/d.py"
    driver = eut.Driver({path: imports + DRIVER.replace("{call}", call)}, path)
    return eut.join_family("effects.fam", driver, golden, blocks)


def test_the_committed_table_is_the_regeneration():
    assert (ROOT / "coverage/effects-unit-table.json").read_text(encoding="utf-8") == eut.dump(eut.build(ROOT))
    done = subprocess.run([sys.executable, str(ROOT / "coverage/effects_unit_table.py"), "--check"], capture_output=True, text=True)
    assert done.returncode == 0, done.stdout + done.stderr


def test_the_join_makes_an_entry_for_a_called_single_block_method_with_a_rule6_case():
    out = join()
    assert [(e["golden_unit"], e["atomic_unit"], e["block"], e["cases"]) for e in out["entries"]] == [
        ("unit", "codex_harness.application.svc:Svc.unit#1", "#1", ["a"])]
    assert out["entries"][0]["driver_call"] == "compare/drivers/reference/d.py:7" and not out["ambiguous"] + out["unmatched"]


def test_negative_control_a_driver_call_to_another_method_is_no_entry():
    out = join(call="other")
    assert out["entries"] == [] and "no driver call" in out["unmatched"][0]["reason"]
    both = [block(1, ["research_rows"]), block(1, ["research_rows"], scope="Svc.other")]
    assert join(call="other", blocks=both)["entries"] == []  # the called method exists in the catalogue, but is not the unit's


def test_negative_control_a_block_whose_buckets_do_not_cover_the_durable_writes_is_ambiguous():
    blocks = [block(1, ["research_rows"]), block(2, ["other_rows"])]
    assert [e["block"] for e in join(blocks=blocks)["entries"]] == ["#1"]  # one block covers: the call reaches it
    out = join(blocks=[block(1, ["other_rows"]), block(2, ["more_rows"])])
    assert out["entries"] == [] and "0 of 2 blocks" in out["ambiguous"][0]["reason"]
    out = join(blocks=[block(1, ["research_rows"]), block(2, ["research_rows", "x"])])  # two qualify
    assert out["entries"] == [] and "2 of 2 blocks" in out["ambiguous"][0]["reason"]
    out = join(blocks=[block(1, ["<dynamic>"]), block(2, [])])  # `<dynamic>` and no literal write never cover
    assert out["entries"] == [] and out["ambiguous"]


def test_negative_control_a_golden_unit_with_no_rule6_case_is_no_entry():
    out = join(golden={"unit": {"success": CASE}})
    assert out["entries"] == [] and "no rule-6 case" in out["unmatched"][0]["reason"]


def test_a_method_name_in_two_imported_classes_is_ambiguous_and_an_unimported_one_is_not_bound():
    two = [block(1, ["research_rows"]), block(1, ["research_rows"], scope="Other.unit")]
    assert join(blocks=two)["ambiguous"][0]["candidates"] == ["Other.unit", "Svc.unit"]
    assert join(imports="")["ambiguous"][0]["reason"].endswith("in no M7 module the driver imports")


def test_s11_au_l3b_a_class_method_declaration_binds_the_named_class_among_two_imported(monkeypatch):
    """A `Class.method` entry of DECLARED_CALLS (REBUILD-DESIGN-v2 §2.9 rule 1): the receiver the AST cannot type is named."""
    two = [block(1, ["research_rows"]), block(1, ["research_rows"], scope="Other.unit")]
    monkeypatch.setitem(eut.DECLARED_CALLS, ("fam", "unit"), "Other.unit")
    out = join(blocks=two)
    assert [e["atomic_unit"] for e in out["entries"]] == ["codex_harness.application.svc:Other.unit#1"] and not out["ambiguous"]
    # control: the declared class is not among the catalogue blocks the driver imports -> no entry, never the other class
    monkeypatch.setitem(eut.DECLARED_CALLS, ("fam", "unit"), "Missing.unit")
    out = join(blocks=two)
    assert out["entries"] == [] and out["ambiguous"][0]["candidates"] == []
    assert out["ambiguous"][0]["reason"].endswith("in no M7 module the driver imports")


def test_s11_au_l3b_a_class_method_declaration_still_needs_the_driver_call(monkeypatch):
    monkeypatch.setitem(eut.DECLARED_CALLS, ("fam", "unit"), "Svc.other")  # the driver calls `unit`, never `other`
    out = join(blocks=[block(1, ["research_rows"]), block(1, ["research_rows"], scope="Svc.other")])
    assert out["entries"] == [] and "no driver call of an M7 method named other" in out["unmatched"][0]["reason"]


@pytest.fixture(scope="module")
def table():
    return json.loads((ROOT / "coverage/effects-unit-table.json").read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def ledger():
    return json.loads((ROOT / "coverage/ledger-coverage.json").read_text(encoding="utf-8"))


def test_every_entry_has_its_driver_call_a_catalogue_block_and_a_rule6_case(table):
    catalogue = {u["key"]: u for u in json.loads(
        (ROOT / eut.CATALOGUE).read_text(encoding="utf-8"))["transaction_blocks"]["units"]}
    assert table["entries"]
    for e in (e for e in table["entries"] if e.get("basis") is None):  # S11 R-L3d-1: rules 1-3 entries; the block_exercise ones are pinned in test_s11_l3d_block_exercise.py
        assert e["atomic_unit"] in catalogue and e["block"] == "#" + e["atomic_unit"].rsplit("#", 1)[1], e
        assert e["cases"] and set(e["cases"]) <= set("abcd"), e
        path, _, line = e["driver_call"].rpartition(":")
        assert len((ROOT / path).read_text(encoding="utf-8").splitlines()) >= int(line) > 0, e
        assert catalogue[e["atomic_unit"]]["scope"].rsplit(".", 1)[-1] in (ROOT / path).read_text(encoding="utf-8").splitlines()[int(line) - 1]
    keys = [(e["family"], e["golden_unit"], e["atomic_unit"]) for e in table["entries"]]
    assert keys == sorted(set(keys))


def test_the_g1_resolutions_are_the_table_entries_on_rows_that_carry_the_pending_item(table, ledger):
    doc = json.loads((ROOT / "coverage/evidence-resolutions.json").read_text(encoding="utf-8"))
    g1 = [e for e in doc["resolutions"] if e["rule"] == "G1"]
    assert g1 == eut.g1_resolutions(table, ledger) and g1
    rows = {r["key"]: r for r in ledger["rows"]}
    for e in g1:
        assert rows[e["key"]]["kind"] == "atomic_unit" and eut.PENDING in rows[e["key"]]["evidence"]
        assert all(i.startswith("compare:effects.") for i in e["replaced_by"])
        for family in (i[len("compare:"):] for i in e["replaced_by"]):
            assert any(t["family"] == family and "atomic_unit:" + t["atomic_unit"] == e["key"] for t in table["entries"])
            assert f"{eut.G1_CITATION}{family}/" in e["citation"]
    # no other pending item was touched: the rows with no entry keep it
    resolved = {e["key"] for e in g1}
    left = [r for r in ledger["rows"] if r["kind"] == "atomic_unit" and eut.PENDING in r["verification"].get("unmet", [])]
    # S11 AU-REC-6a: _finish#1 was the last row to carry the item in its unmet list; with it joined none remains
    assert not left and not {r["key"] for r in left} & resolved
