from __future__ import annotations

from typing import ContextManager, Protocol


class Transaction(Protocol):
    def get(self, bucket: str, key: str) -> dict | None: ...
    def put(self, bucket: str, key: str, body: dict) -> None: ...
    def scan(self, bucket: str) -> list[dict]: ...
    def records(self) -> list[dict]: ...
    def entries(self, bucket: str, after: str = "", limit: int = 100) -> list[dict]: ...


class Store(Protocol):
    def transaction(self) -> ContextManager[Transaction]: ...


class MessageDeliveryError(RuntimeError):
    """Transport failed; delivery may have happened before the response was lost."""


class SpoolFull(RuntimeError):
    """The bounded observation spool cannot take another record; the caller counts and reports."""


class ObservationSpool(Protocol):
    """One process run's append-only durable record store (INV-OBSERVATION-001)."""
    process_run_id: str

    def append(self, kind: str, event: dict) -> int: ...
    def close(self) -> None: ...


class ObservationDirectory(Protocol):
    """What a collector, the executor guard and an operator read beside the spool."""

    def spool_files(self) -> list: ...
    def read(self, path, offset: int = 0): ...
    def acknowledged(self, path) -> int: ...
    def acknowledge(self, path, offset: int, consumed: int) -> None: ...
    def write_health(self, process_run_id: str, record: dict) -> None: ...
    def read_health(self) -> list[dict]: ...
    def record_termination(self, record_id: str, record: dict) -> None: ...
    def pending_terminations(self, task_id: str | None = None) -> list[dict]: ...
    def resolve_termination(self, record_id: str, resolution: dict) -> dict: ...


class MessageBus(Protocol):
    def validate(self, message: dict) -> dict: ...
    def publish(self, message: dict) -> str: ...


class Runtime(Protocol):
    def run(self, prompt: str, cwd: str, schema: dict, timeout: int = 120) -> dict: ...


class Knowledge(Protocol):
    def index_python(self, root: str) -> dict: ...
    def query(self, text: str, depth: int = 1, limit: int = 12) -> list[dict]: ...


class SourceControl(Protocol):
    def prepare(self, task_id: str, base: str) -> dict: ...
    def capture(self, workspace: dict) -> dict: ...
    def inspect(self, revision: str, base: str) -> dict: ...
    def publish(self, candidate: dict, title: str, body: str) -> dict: ...
    def merge(self, candidate: dict) -> dict: ...


class ArtifactStore(Protocol):
    def put(self, body: str, source: str) -> dict: ...
    def read(self, reference: str, start: int = 0, length: int = 8000) -> str: ...


class AuditArtifacts(ArtifactStore, Protocol):
    def document(self, reference: str) -> dict: ...
    def inspect(self, reference: str) -> dict: ...


class SourceVerifier(Protocol):
    def verify(self, source, entries) -> dict: ...
