from __future__ import annotations

from typing import ContextManager, Protocol


class Transaction(Protocol):
    def get(self, bucket: str, key: str) -> dict | None: ...
    def put(self, bucket: str, key: str, body: dict) -> None: ...
    def scan(self, bucket: str) -> list[dict]: ...
    def records(self) -> list[dict]: ...
    def entries(self, bucket: str, after: str = "", limit: int = 100) -> list[dict]: ...


class Store(Protocol):
    def transaction(self) -> ContextManager[Transaction]: ...


class MessageDeliveryError(RuntimeError):
    """Transport failed; delivery may have happened before the response was lost."""


class MessageBus(Protocol):
    def validate(self, message: dict) -> dict: ...
    def publish(self, message: dict) -> str: ...


class Runtime(Protocol):
    def run(self, prompt: str, cwd: str, schema: dict, timeout: int = 120) -> dict: ...


class Knowledge(Protocol):
    def index_python(self, root: str) -> dict: ...
    def query(self, text: str, depth: int = 1, limit: int = 12) -> list[dict]: ...


class SourceControl(Protocol):
    def prepare(self, task_id: str, base: str) -> dict: ...
    def capture(self, workspace: dict) -> dict: ...
    def inspect(self, revision: str, base: str) -> dict: ...
    def publish(self, candidate: dict, title: str, body: str) -> dict: ...
    def merge(self, candidate: dict) -> dict: ...


class ArtifactStore(Protocol):
    def put(self, body: str, source: str) -> dict: ...
    def read(self, reference: str, start: int = 0, length: int = 8000) -> str: ...


class AuditArtifacts(ArtifactStore, Protocol):
    def document(self, reference: str) -> dict: ...
    def inspect(self, reference: str) -> dict: ...


class SourceVerifier(Protocol):
    def verify(self, source, entries) -> dict: ...
